Csv2Json.MVC/Models/ErrorViewModel.cs
namespace Csv2Json.MVC.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Csv2Json.MVC/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Csv2Json.MVC.Models;

namespace Csv2Json.MVC.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    public IActionResult TransformCsv2Json()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Csv2Json.MVC/Controllers/TransformController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Csv2Json.MVC.Models;
using Csv2Json.Services;
using Microsoft.AspNetCore.Http;
using System;
using System.IO;

namespace Csv2Json.MVC.Controllers;

public class TransformController : Controller
{
    private readonly ILogger<TransformController> _logger;
    private readonly ICsv2JsonTransform _csv2JsonTransform;

    public TransformController(ILogger<TransformController> logger, ICsv2JsonTransform csv2JsonTransform)
    {
        _logger = logger;
        _csv2JsonTransform = csv2JsonTransform;
    }

    public IActionResult Index()
    {
        return View();
    }

    [HttpPost]
    public JsonResult Transform(string csv)
    {
        try
        {
            return Json(_csv2JsonTransform.Transform(csv));
        }
        catch (FormatException e)
        {
            return Json(e.Message);
        }
    }

    [HttpPost]
    public JsonResult FileTransform(IFormFile fileCsv)
    {
        using (var reader = new StreamReader(fileCsv.OpenReadStream()))
        {
            var csv = reader.ReadToEnd();
            return Json(_csv2JsonTransform.Transform(csv));
        }
    }
}

Csv2Json.MVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Csv2Json.MVC/Views/Home/TransformCsv2Json.cshtml
@{
    ViewData["Title"] = "Csv2Json";
}
<h1>@ViewData["Title"]</h1>

<p>Use this page to transform csv.</p>

Csv2Json.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Csv2Json.MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Csv2Json.MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Csv2Json.MVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Transform" asp-action="Index">Transform</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Csv2Json.MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Csv2Json.MVC/Views/Transform/Index.cshtml
@{
    ViewData["Title"] = "Transform Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <table>
        <tr>
            <td><textarea class="form-control" rows="10" cols="30" name="csv" id="inputcsv"></textarea></td>
            <td><input type="submit" value="Transform" class="btn btn-primary" onclick="JsonTextTransformClick()" />
            </td>
            <td><textarea class="form-control" rows="10" cols="30" id="resultText"></textarea></td>
        </tr>
    </table>
</div>
<br />
<br />

<form id="form1" method="post" enctype="multipart/form-data">
    <input name="fileCsv" id="f1" type="file" />
    <input type="submit" id="btnCsv" value="Отправить" onclick="FileMethod()" />
</form>

<script>
    document.getElementById("form1").addEventListener("submit", function(event)
    {  
        event.preventDefault();
    });


    function FileMethod() {
        var formData = new FormData(document.getElementById("form1"));
        
        $.ajax({
            url: "/Transform/FileTransform",
            method: "Post",
            cache: false,
            contentType: false,
            data: formData,
            processData: false,
            success: function (product) {
                $('#resultText').val(product);
            }
        })
    };
</script>

<script>
    function JsonTextTransformClick() {
        $.ajax({
            url: "Transform/Transform",
            method: "Post",
            data: { 'csv': $('#inputcsv').val() },
            success: function (product) {
                $('#resultText').val(product);
            }
        })
    };
</script>